/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CheckForm: typeof import('./src/components/CheckForm.vue')['default']
    CitySelect: typeof import('./src/components/CitySelect.vue')['default']
    CompanyTypeSelect: typeof import('./src/components/CompanyTypeSelect.vue')['default']
    copy: typeof import('./src/components/TheHeader copy.vue')['default']
    IndustryTypeSelect: typeof import('./src/components/IndustryTypeSelect.vue')['default']
    MNamingDesc: typeof import('./src/components/m/MNamingDesc.vue')['default']
    MNamingForm: typeof import('./src/components/m/MNamingForm.vue')['default']
    NaiveProvider: typeof import('./src/components/NaiveProvider.vue')['default']
    NamingDesc: typeof import('./src/components/NamingDesc.vue')['default']
    NamingForm: typeof import('./src/components/NamingForm.vue')['default']
    NamingRes: typeof import('./src/components/NamingRes.vue')['default']
    RegisterDesc: typeof import('./src/components/RegisterDesc.vue')['default']
    ResultModal: typeof import('./src/components/ResultModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScopeForm: typeof import('./src/components/ScopeForm.vue')['default']
    SubmitModal: typeof import('./src/components/SubmitModal.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    'TheHeader copy': typeof import('./src/components/TheHeader copy.vue')['default']
  }
}
